spring.application.name=CompanyCart
spring.datasource.url=jdbc:postgresql://localhost:5432/org_cart_db
spring.datasource.username=egbelyansky
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.enabled=false

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.datasource.hikari.connection-timeout=20000

dadata.api.key=bf254ed41e3f21eff3882619dfd01f8a10914d11
dadata.api.url=https://suggestions.dadata.ru/suggestions/api/4_1/rs/findById/party
dadata.api.timeout=10000

logging.level.ru.companycart=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n
logging.file.name=logs/application.log